README.md
=> Update CI status in the README

README.md
Now it reflects our organization's badge
=> Fix status badge in readme

docs/DeveloperGuide.md
Updated glossary with important terms for the project.
=> Update glossary in developer guide with important terms and definitions

docs/DeveloperGuide.md
=> update target user profile and value proposition in DG

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/employee/Address.java, src/main/java/seedu/address/model/employee/Employee.java, src/main/java/seedu/address/model/employee/Name.java, src/main/java/seedu/address/model/employee/Role.java, src/main/java/seedu/address/model/employee/Team.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedEmployee.java, src/main/java/seedu/address/ui/EmployeeCard.java, src/main/resources/view/EmployeeListCard.fxml, src/test/java/seedu/address/storage/JsonAdaptedEmployeeTest.java, src/test/java/seedu/address/testutil/EmployeeBuilder.java, src/test/java/seedu/address/testutil/TypicalEmployees.java
Add the prefixes (T/) team and (r/) role to employee. 
Update changes to associated classes.
Update test cases to accommodate for the new fields in employee.
Update visuals on the GUI to display the two new prefixes.
Users will be able to track the team and role of their employees more effectively.
=> Add prefixes contacts

src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/employee/Employee.java, src/main/java/seedu/address/model/employee/Role.java, src/main/java/seedu/address/model/employee/UniqueId.java, src/main/java/seedu/address/model/employee/UniqueIdGenerator.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedEmployee.java, src/main/java/seedu/address/storage/JsonAddressBookStorage.java, src/main/java/seedu/address/storage/JsonSerializableAddressBook.java, src/main/java/seedu/address/ui/EmployeeCard.java, src/main/resources/view/EmployeeListCard.fxml, src/test/data/JsonAddressBookStorageTest/invalidAndValidEmployeeAddressBook.json, src/test/data/JsonAddressBookStorageTest/invalidEmployeeAddressBook.json, src/test/data/JsonSerializableAddressBookTest/duplicateEmployeeAddressBook.json, src/test/data/JsonSerializableAddressBookTest/invalidEmployeeAddressBook.json, src/test/data/JsonSerializableAddressBookTest/typicalEmployeesAddressBook.json, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/model/employee/EmployeeTest.java, src/test/java/seedu/address/storage/JsonAdaptedEmployeeTest.java, src/test/java/seedu/address/testutil/EmployeeBuilder.java, src/test/java/seedu/address/testutil/TypicalEmployees.java
- Automatically generated unique id for each user when added.
- ID is showcased on GUI as well.
=> Branch uniqueid

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/model/employee/Employee.java, src/test/data/JsonSerializableAddressBookTest/typicalEmployeesAddressBook.json, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/seedu/address/logic/parser/AddCommandParserTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/model/employee/EmployeeTest.java, src/test/java/seedu/address/testutil/TypicalEmployees.java
Still need to fix the remaining 2 test classes
=> Fix failing test classes

src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
=> Branch delete by uid

docs/diagrams/AddSequenceDiagram.puml
Include a detailed PlantUML sequence diagram illustrating the process flow of the AddCommand in the application. This diagram captures the interactions between LogicManager, AddressBookParser, AddCommandParser, AddCommand, Employee, Model, and Storage classes, aligning with the current class structure and method calls.
=> Add sequence diagram for AddCommand flow

build.gradle, docs/UserGuide.md
Change jar file name. Update release link.
=> Update User guide

src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/logic/parser/DeleteCommandParser.java, src/test/java/seedu/address/logic/commands/DeleteCommandTest.java, src/test/java/seedu/address/logic/commands/FilterCommandTest.java, src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java, src/test/java/seedu/address/model/ModelStubWithEmployee.java
Adjust parse method to check for name input after UID and index parsing
=> Fix bug regarding name-based deletion

docs/DeveloperGuide.md
The Developer Guide has been updated to include details about the implementation of the delete command. This includes the handling of deletion by name in case of duplicate names and deletion by unique id. This information provides clarity on how these features are implemented and can assist other developers in understanding the codebase.
=> Update Developer Guide with delete command details

docs/DeveloperGuide.md
Update developer guide with UID design details
=> Update Developer Guide with UID info

docs/DeveloperGuide.md, docs/diagrams/ArchitectureSequenceDiagram.puml, docs/diagrams/BetterModelClassDiagram.puml, docs/diagrams/DeleteSequenceDiagram.puml, docs/diagrams/ModelClassDiagram.puml, docs/diagrams/UiClassDiagram.puml, docs/diagrams/UpdatedEmployeeClassDiagram.puml, docs/team/quelinxiao.md
add 'AddCommand' under 'Implementation' in developer guide.
refactor 'Person' to 'Employee' in all UML diagrams.
=> update DG to include AddCommand implementation

src/main/resources/view/DarkTheme.css, src/main/resources/view/Extensions.css, src/main/resources/view/MainWindow.fxml
change the dark theme design and moved CLI to the bottom of the app.
=> Improve UI aesthetics

docs/UserGuide.md
The user guide previously did not detail the extensive filtering capabilities of the application, specifically omitting the ability to filter employees by name, tags, role, and team in the filter feature section. This omission limited the guide's usefulness and completeness.
To rectify this and provide a thorough understanding of the filter command, the following enhancements have been made:
* Updated the `filter` section to encompass filtering by name, tags, role, and team, reflecting the full functionality of the command.
* Revised examples to showcase the versatility of filtering by different criteria, both individually and in combination.
These updates ensure the user guide accurately mirrors the application's features, empowering users to leverage the filter command to its full …
=> Add comprehensive filtering options to user guide

docs/UserGuide.md
Update user guide with format and examples of addTask, mark and unmark tasks functionality
=> Add documentation for addTask, mark and unmark in user guide

src/main/java/seedu/address/logic/parser/FilterCommandParser.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/DeleteCommandTest.java, src/test/java/seedu/address/logic/commands/FilterCommandTest.java, src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java, src/test/java/seedu/address/model/ModelStub.java, src/test/java/seedu/address/model/ModelStubWithEmployees.java, src/test/java/seedu/address/model/ModelStubWithFilteredEmployeeList.java
Extracted out the private class of Model Stub in AddCommand.java to a class of its own so that it could be used in other test classes as well.
=> Credit Use of Model Stubs

src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/logic/commands/FilterCommand.java, src/main/java/seedu/address/logic/commands/MarkTaskCommand.java, src/main/java/seedu/address/logic/commands/UnmarkTaskCommand.java, src/main/java/seedu/address/logic/parser/DeleteCommandParser.java, src/main/java/seedu/address/logic/parser/FilterCommandParser.java, src/main/java/seedu/address/model/util/CommandUtil.java, src/test/java/seedu/address/logic/commands/DeleteCommandTest.java, src/test/java/seedu/address/logic/commands/FilterCommandTest.java, src/test/java/seedu/address/logic/commands/UnmarkTaskCommandTest.java, src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Task-related command classes like MarkTaskCommand and UnmarkTaskCommand had issues with code quality concerning exception handling, method structure, and overall readability.
The existing implementation mixed concerns, such as constructing objects and validating input within constructors, leading to less clear and maintainable code. Moreover, the exception messages were generic and did not provide enough context for understanding the nature of the error.
Refactored the command classes to separate concerns, moving input validation to the execute method and enhancing exception handling for more descriptive messages. Introduced Stream API usage for cleaner and more efficient employee lookup, and added logging for better debugging and error tracking.
This approach enhances the …
=> Improve code quality of task command classes

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/AddTaskCommand.java, src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java, src/main/java/seedu/address/logic/commands/UnmarkTaskCommand.java, src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java, src/main/java/seedu/address/logic/parser/DeleteTaskCommandParser.java, src/main/java/seedu/address/logic/parser/MarkTaskCommandParser.java, src/main/java/seedu/address/logic/parser/UnmarkTaskCommandParser.java, src/main/java/seedu/address/model/task/Description.java
Messages updated for comprehensive feedback to the user
=> In app msg

docs/DeveloperGuide.md, docs/diagrams/DeleteSequenceDiagram.puml
The Developer Guide has been updated to reflect the current functionalities of ContactSwift more accurately. Changes include the revision of use cases to align with the latest version of the software, updating the Non-Functional Requirements to eliminate redundancy and improve specificity, and the refinement of user stories to better represent user interactions and needs.
- Revised use cases now correctly depict the process of adding, deleting, and editing employee records, as well as task management, according to the functionalities provided in ContactSwift v1.4.
- Enhanced Non-Functional Requirements to address performance efficiency, user efficiency, data security, and memory usage, ensuring they are distinct and cover a broader scope of the application's operational aspects.
- Updated …
=> Update Developer Guide for Enhanced Clarity and Accuracy

docs/DeveloperGuide.md
Edit the Developer Guide to remove any outdated information. For example, any references to Person while our model has changed to Employee.
=> Remove outdated information in DG

docs/DeveloperGuide.md
Update Developer Guide with implementation details for the TaskList and other features
=> 148-update-dg-implementation-details

src/main/java/seedu/address/logic/parser/DeleteTaskCommandParser.java, src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java, src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java, src/test/java/seedu/address/logic/parser/AddTaskCommandParserTest.java, src/test/java/seedu/address/logic/parser/DeleteTaskCommandParserTest.java
improve the code coverage of addTaskCommand, deleteTaskCommand, and their respective parsers.
=> improve code coverage of parser and command

docs/DeveloperGuide.md, docs/UserGuide.md
Remove the <a> tag from markdown
=> Remove anchor

docs/DeveloperGuide.md, docs/UserGuide.md
- Updates links
- Update formatting
- Updated section order
=> Fix UG and DG

docs/UserGuide.md, docs/diagrams/BetterModelClassDiagram.puml, docs/diagrams/ModelClassDiagram.puml, docs/diagrams/StorageClassDiagram.puml, docs/diagrams/UpdatedEmployeeClassDiagram.puml
=> Fix UG bugs and update UML

docs/DeveloperGuide.md
The info box boundaries were wrong. Updated now
=> Fix DG Manual Testing Formatting

docs/diagrams/BetterModelClassDiagram.puml, docs/diagrams/ModelClassDiagram.puml
Update UML diagrams to match current TaskList specifications
=> 169-uml-modifications

docs/DeveloperGuide.md
Add the Planned Enhancements appendix in developer guide.
=> 139-dg-planned-enhancements
